version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - mern-net
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "6300:6300"
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge
